variables:
  - &nodejs_image 'node:20-alpine'
  - &buildkit_image 'moby/buildkit:v0.31.0'

when:
  - event: [pull_request, push, tag]

steps:
  - name: install-lint-check
    image: *nodejs_image
    commands:
      - npm ci
      - npm run check
    when:
      event: [push, pull_request]
      branch: [dev, main]

  - name: build-and-push-nightly
    image: *buildkit_image
    commands:
      - buildctl build \
          --addr tcp://buildkit.buildkit.svc.cluster.local:2395 \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --output type=image,name=registry.xheize.cc/xheize-cc:nightly-${CI_COMMIT_SHA:0:8},push=true \
          --output type=image,name=registry.xheize.cc/xheize-cc:nightly,push=true
    when:
      event: [push, cron, manual]
      branch: [main]

  - name: build-and-push
    image: *buildkit_image
    commands:
      - buildctl build \
          --addr tcp://buildkit.buildkit.svc.cluster.local:2395 \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --output type=image,name=registry.xheize.cc/xheize-cc:${CI_COMMIT_TAG},push=true \
          --output type=image,name=registry.xheize.cc/xheize-cc:latest,push=true
    when:
      event: [tag]
      branch: [main]
